### ISSUE TITLE
Owner and Withdrawal of bids 

### ISSUE THREAD

**Issue by jgcogsystematictrading** [Ashar2shahid/airsearcher-contracts#2]
We need to set the deployer of the contract to be an owner. Then a function where the owner can specify an address that can then withdraw the native tokens from the contract.

**Comment by jgcogsystematictrading** [comment]
Or you can just have the deployer specify the address that can withdraw funds in the constuctor.

**Comment by Ashar2shahid** [comment]
I added an only owner withdrawal mechanism for now. Can change it later I think
